### PR TITLE
Fix: misc ui changes (Gitcoin)

### PR DESCRIPTION
**Pull request by tpscrpt**
Hey, saw #13 and thought I'd give it a shot.

These fixes should make you happy.

1. Remove "button" from ListItems to make them clickable links instead
2. Move the list into the drawer header and restyle the button a little bit

### CODE REVIEW

**Comment by benoror** [comment]
@JeremiGendron 	awesome! already approved on Gitcoin, gonna check this out ASAP

**Review by benoror — CHANGES_REQUESTED** [review]
@JeremiGendron 	just saw your changes, could you please:

- [ ] Revert the `<Divider />` and style of the `drawerHeader` (that wasn't part of the bounty issue)
- [ ] Finish fixing remaining buttons (the circular ones, part of the bounty issue)
- [ ] Fix whitespace/margin left to the main content (also part of the bounty issue)

**Comment by tpscrpt** [comment]
@benoror which remaining buttons? The profile + circularIcon button gets unstyled when it's not a button anymore. Contacts? Or UI like (+) buttons.

**Comment by benoror** [comment]
> @benoror which remaining buttons? The profile + circularIcon button gets unstyled when it's not a button anymore. Contacts? Or UI like (+) buttons.

These buttons:

**Comment by tpscrpt** [comment]
Ok, on it

**Comment by tpscrpt** [comment]
@benoror  I'm not sure whether you want Text-only or Icon next to text for those, so I will not continue with the bounty. Submitting clean PR with changes so far.

**Comment by tpscrpt** [comment]
@benoror Nevermind! Looks like you took it into your own hands.

**Comment by benoror** [comment]
@JeremiGendron I would be glad to commit long term for the project if I like what I see... I need a design-driven React expert.

btw, did you try running the app? You need to sign in using Blockstack: http://blockstack.org

**Comment by tpscrpt** [comment]
I'm not an expert, but I can get the job done. I have a lot of time too.

**Comment by benoror** [comment]
> I'm not an expert, but I can get the job done. I have a lot of time too.

Awesome, please stick with the requirements for now, and feel free to improve other areas as well. Thanks!

**Pull request closed without merging**
